call "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\env\Scripts\activate.bat"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka1.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka2.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka3.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka4.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka5.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka6.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka7.py"
start python "C:\Users\zache\OneDrive\Desktop\VS Code Files\Python\IPFS Rarity Tool\Meka\FileFolder\Meka8.py"